services:
  customerdb:
    image: postgres:15-alpine
    container_name: customerdb
    ports:
      - "5448:5432"
    environment:
      - POSTGRES_DB=customerdb
      - POSTGRES_USER=spring
      - POSTGRES_PASSWORD=spring
    restart: always
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
